### ISSUE TITLE
Produces unexpected results for n !== 1000

### ISSUE THREAD

**Issue by rreusser** [ataber/mesh-simplify#2]
The example with n = 1000 seems to work, but if I start reducing the number of vertices, it starts to produce strange results. For the example script with n = 500:

<img width="355" alt="screen shot 2017-11-19 at 1 37 27 pm" src="https://user-images.githubusercontent.com/572717/32995826-02380be8-cd2f-11e7-9567-580da9bfad7e.png">

It's possible it's a problem with the meat of the algorithm, but it seems maybe more likely that it's some sort of corruption thing with the numbering somewhere along the way.

**Comment by rreusser** [comment]
With wireframe:

<img width="720" alt="screen shot 2017-11-19 at 1 43 04 pm" src="https://user-images.githubusercontent.com/572717/32995869-9a55c4f6-cd2f-11e7-957d-0db46f595eaf.png">

**Comment by ataber** [comment]
For some reason I didn't get a notification about this. Thanks for bringing this up - I'll look into it!

**Comment by ataber** [comment]
Okay I think I found the issue. 

[This line](https://github.com/ataber/mesh-simplify/blob/ad819cd6183c7aff60391ec4305072290fe97c35/index.js#L197) (as well as line 190), should have `vertices[edge.pair[(edge.pair.indexOf(i2) + 1) % 2]]`. Whoops!

Now produces nice chunky low-poly things like 
![screen shot 2017-12-24 at 10 52 30 pm](https://user-images.githubusercontent.com/1509787/34334674-441517ba-e8fd-11e7-8fdf-e0bfd2781dde.png)

Will push an update shortly

**Comment by rreusser** [comment]
Thanks for debugging this! So excited to try it. I've been trying to make sense of mesh geometry lately, so decimating a bit might be a huge help. Can't wait to try it!
